import pyautogui as pa
import time

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/gnNjMqZgnO4?t=600', interval=0)
pa.press('enter', interval=0.1)
time.sleep(3)
pa.press('f', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(10)
pa.hotkey('altleft', 'f6')
pa.press('f', interval=0.1)
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/b17Nsc8LOLs?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(10)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/nrdcjbJ7PbI?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/HnVTE4vM8no?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/rallY-QTZU0?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/sqjRrpXWdFE?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/L7QWGzJeYZ4?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/qY4MCNRpGPo?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/d2EE_cLaANk?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/vCYkAKa63NA?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')

pa.hotkey('win', 'r')
pa.write('chrome.exe https://youtu.be/BtqG_pcTKXE?t=600', interval=0)
pa.press('enter', interval=0.1)
pa.hotkey('altleft', 'f5')
time.sleep(5)
pa.hotkey('altleft', 'f6')
pa.moveTo(1900, 20)
pa.click(button='left')